<?php

namespace Proxies\__CG__\Sonata\Bundle\DemoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Color extends \Sonata\Bundle\DemoBundle\Entity\Color implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'r', 'g', 'b', 'material', 'enabled');
        }

        return array('__isInitialized__', 'r', 'g', 'b', 'material', 'enabled');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Color $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($enabled));

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', array());

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setB($b)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setB', array($b));

        return parent::setB($b);
    }

    /**
     * {@inheritDoc}
     */
    public function getB()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getB();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getB', array());

        return parent::getB();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaterial(\Sonata\Bundle\DemoBundle\Entity\Material $material)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaterial', array($material));

        return parent::setMaterial($material);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaterial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaterial', array());

        return parent::getMaterial();
    }

    /**
     * {@inheritDoc}
     */
    public function setG($g)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setG', array($g));

        return parent::setG($g);
    }

    /**
     * {@inheritDoc}
     */
    public function getG()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getG();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getG', array());

        return parent::getG();
    }

    /**
     * {@inheritDoc}
     */
    public function setR($r)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setR', array($r));

        return parent::setR($r);
    }

    /**
     * {@inheritDoc}
     */
    public function getR()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getR();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getR', array());

        return parent::getR();
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectIdentifier', array());

        return parent::getObjectIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
