<?php

namespace Proxies\__CG__\Application\Sonata\OrderBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \Application\Sonata\OrderBundle\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'reference', 'paymentMethod', 'deliveryMethod', 'currency', 'status', 'paymentStatus', 'deliveryStatus', 'validatedAt', 'username', 'totalInc', 'totalExcl', 'deliveryCost', 'deliveryVat', 'billingName', 'billingPhone', 'billingAddress1', 'billingAddress2', 'billingAddress3', 'billingCity', 'billingPostcode', 'billingCountryCode', 'billingFax', 'billingEmail', 'billingMobile', 'shippingName', 'shippingPhone', 'shippingAddress1', 'shippingAddress2', 'shippingAddress3', 'shippingCity', 'shippingPostcode', 'shippingCountryCode', 'shippingFax', 'shippingEmail', 'shippingMobile', 'orderElements', 'createdAt', 'updatedAt', 'customer', 'locale');
        }

        return array('__isInitialized__', 'id', 'reference', 'paymentMethod', 'deliveryMethod', 'currency', 'status', 'paymentStatus', 'deliveryStatus', 'validatedAt', 'username', 'totalInc', 'totalExcl', 'deliveryCost', 'deliveryVat', 'billingName', 'billingPhone', 'billingAddress1', 'billingAddress2', 'billingAddress3', 'billingCity', 'billingPostcode', 'billingCountryCode', 'billingFax', 'billingEmail', 'billingMobile', 'shippingName', 'shippingPhone', 'shippingAddress1', 'shippingAddress2', 'shippingAddress3', 'shippingCity', 'shippingPostcode', 'shippingCountryCode', 'shippingFax', 'shippingEmail', 'shippingMobile', 'orderElements', 'createdAt', 'updatedAt', 'customer', 'locale');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', array());

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullDelivery($sep = ', ')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullDelivery', array($sep));

        return parent::getFullDelivery($sep);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryAsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryAsArray', array());

        return parent::getDeliveryAsArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullBilling($sep = ', ')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullBilling', array($sep));

        return parent::getFullBilling($sep);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAsArray', array());

        return parent::getBillingAsArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', array($reference));

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', array());

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethod($paymentMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethod', array($paymentMethod));

        return parent::setPaymentMethod($paymentMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethod', array());

        return parent::getPaymentMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryMethod($deliveryMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryMethod', array($deliveryMethod));

        return parent::setDeliveryMethod($deliveryMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryMethod', array());

        return parent::getDeliveryMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency(\Sonata\Component\Currency\CurrencyInterface $currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentStatus($paymentStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentStatus', array($paymentStatus));

        return parent::setPaymentStatus($paymentStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentStatus', array());

        return parent::getPaymentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentStatusName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentStatusName', array());

        return parent::getPaymentStatusName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryStatus($deliveryStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryStatus', array($deliveryStatus));

        return parent::setDeliveryStatus($deliveryStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryStatus', array());

        return parent::getDeliveryStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryStatusName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryStatusName', array());

        return parent::getDeliveryStatusName();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidatedAt(\DateTime $validatedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidatedAt', array($validatedAt));

        return parent::setValidatedAt($validatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidatedAt', array());

        return parent::getValidatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalInc($totalInc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalInc', array($totalInc));

        return parent::setTotalInc($totalInc);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalInc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalInc', array());

        return parent::getTotalInc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalExcl($totalExcl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalExcl', array($totalExcl));

        return parent::setTotalExcl($totalExcl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalExcl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalExcl', array());

        return parent::getTotalExcl();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryCost($deliveryCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryCost', array($deliveryCost));

        return parent::setDeliveryCost($deliveryCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryCost', array());

        return parent::getDeliveryCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryVat($deliveryVat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryVat', array($deliveryVat));

        return parent::setDeliveryVat($deliveryVat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryVat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryVat', array());

        return parent::getDeliveryVat();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingName($billingName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingName', array($billingName));

        return parent::setBillingName($billingName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingName', array());

        return parent::getBillingName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingPhone($billingPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingPhone', array($billingPhone));

        return parent::setBillingPhone($billingPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingPhone', array());

        return parent::getBillingPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress1($billingAddress1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress1', array($billingAddress1));

        return parent::setBillingAddress1($billingAddress1);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress1', array());

        return parent::getBillingAddress1();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress2($billingAddress2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress2', array($billingAddress2));

        return parent::setBillingAddress2($billingAddress2);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress2', array());

        return parent::getBillingAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress3($billingAddress3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress3', array($billingAddress3));

        return parent::setBillingAddress3($billingAddress3);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress3', array());

        return parent::getBillingAddress3();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingCity($billingCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingCity', array($billingCity));

        return parent::setBillingCity($billingCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingCity', array());

        return parent::getBillingCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingPostcode($billingPostcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingPostcode', array($billingPostcode));

        return parent::setBillingPostcode($billingPostcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingPostcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingPostcode', array());

        return parent::getBillingPostcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingCountryCode($billingCountryCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingCountryCode', array($billingCountryCode));

        return parent::setBillingCountryCode($billingCountryCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingCountryCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingCountryCode', array());

        return parent::getBillingCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingFax($billingFax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingFax', array($billingFax));

        return parent::setBillingFax($billingFax);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingFax', array());

        return parent::getBillingFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingEmail($billingEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingEmail', array($billingEmail));

        return parent::setBillingEmail($billingEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingEmail', array());

        return parent::getBillingEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingMobile($billingMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingMobile', array($billingMobile));

        return parent::setBillingMobile($billingMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingMobile', array());

        return parent::getBillingMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingName($shippingName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingName', array($shippingName));

        return parent::setShippingName($shippingName);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingName', array());

        return parent::getShippingName();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingPhone($shippingPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingPhone', array($shippingPhone));

        return parent::setShippingPhone($shippingPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingPhone', array());

        return parent::getShippingPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress1($shippingAddress1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress1', array($shippingAddress1));

        return parent::setShippingAddress1($shippingAddress1);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress1', array());

        return parent::getShippingAddress1();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress2($shippingAddress2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress2', array($shippingAddress2));

        return parent::setShippingAddress2($shippingAddress2);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress2', array());

        return parent::getShippingAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress3($shippingAddress3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress3', array($shippingAddress3));

        return parent::setShippingAddress3($shippingAddress3);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress3', array());

        return parent::getShippingAddress3();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingCity($shippingCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingCity', array($shippingCity));

        return parent::setShippingCity($shippingCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingCity', array());

        return parent::getShippingCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingPostcode($shippingPostcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingPostcode', array($shippingPostcode));

        return parent::setShippingPostcode($shippingPostcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingPostcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingPostcode', array());

        return parent::getShippingPostcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingCountryCode($shippingCountryCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingCountryCode', array($shippingCountryCode));

        return parent::setShippingCountryCode($shippingCountryCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingCountryCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingCountryCode', array());

        return parent::getShippingCountryCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingFax($shippingFax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingFax', array($shippingFax));

        return parent::setShippingFax($shippingFax);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingFax', array());

        return parent::getShippingFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingEmail($shippingEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingEmail', array($shippingEmail));

        return parent::setShippingEmail($shippingEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingEmail', array());

        return parent::getShippingEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMobile($shippingMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMobile', array($shippingMobile));

        return parent::setShippingMobile($shippingMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMobile', array());

        return parent::getShippingMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderElements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderElements', array());

        return parent::getOrderElements();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderElement(\Sonata\Component\Order\OrderElementInterface $orderElement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderElement', array($orderElement));

        return parent::addOrderElement($orderElement);
    }

    /**
     * {@inheritDoc}
     */
    public function isValidated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValidated', array());

        return parent::isValidated();
    }

    /**
     * {@inheritDoc}
     */
    public function isCancelled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCancelled', array());

        return parent::isCancelled();
    }

    /**
     * {@inheritDoc}
     */
    public function isPending()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPending', array());

        return parent::isPending();
    }

    /**
     * {@inheritDoc}
     */
    public function isOpen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOpen', array());

        return parent::isOpen();
    }

    /**
     * {@inheritDoc}
     */
    public function isCancellable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCancellable', array());

        return parent::isCancellable();
    }

    /**
     * {@inheritDoc}
     */
    public function isError()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isError', array());

        return parent::isError();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderElements(\Sonata\Component\Order\OrderElementInterface $orderElements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderElements', array($orderElements));

        return parent::addOrderElements($orderElements);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderElements($orderElements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderElements', array($orderElements));

        return parent::setOrderElements($orderElements);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\Sonata\Component\Customer\CustomerInterface $customer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusName', array());

        return parent::getStatusName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocale', array($locale));

        return parent::setLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocale', array());

        return parent::getLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function getVat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVat', array());

        return parent::getVat();
    }

    /**
     * {@inheritDoc}
     */
    public function getVatAmounts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVatAmounts', array());

        return parent::getVatAmounts();
    }

}
