<?php

namespace Proxies\__CG__\Application\Sonata\BasketBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Basket extends \Application\Sonata\BasketBundle\Entity\Basket implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'basketElements', 'positions', 'cptElement', 'inBuild', 'productPool', 'billingAddress', 'paymentMethod', 'paymentMethodCode', 'billingAddressId', 'deliveryAddress', 'deliveryMethod', 'deliveryAddressId', 'deliveryMethodCode', 'customer', 'customerId', 'options', 'locale', 'currency');
        }

        return array('__isInitialized__', 'id', 'basketElements', 'positions', 'cptElement', 'inBuild', 'productPool', 'billingAddress', 'paymentMethod', 'paymentMethodCode', 'billingAddressId', 'deliveryAddress', 'deliveryMethod', 'deliveryAddressId', 'deliveryMethodCode', 'customer', 'customerId', 'options', 'locale', 'currency');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Basket $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBasketElements($basketElements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBasketElements', array($basketElements));

        return parent::setBasketElements($basketElements);
    }

    /**
     * {@inheritDoc}
     */
    public function reset($full = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'reset', array($full));

        return parent::reset($full);
    }

    /**
     * {@inheritDoc}
     */
    public function setProductPool(\Sonata\Component\Product\Pool $pool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductPool', array($pool));

        return parent::setProductPool($pool);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductPool()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductPool', array());

        return parent::getProductPool();
    }

    /**
     * {@inheritDoc}
     */
    public function isEmpty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEmpty', array());

        return parent::isEmpty();
    }

    /**
     * {@inheritDoc}
     */
    public function isValid($elementsOnly = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValid', array($elementsOnly));

        return parent::isValid($elementsOnly);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryMethod(\Sonata\Component\Delivery\ServiceDeliveryInterface $method = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryMethod', array($method));

        return parent::setDeliveryMethod($method);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryMethod', array());

        return parent::getDeliveryMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryAddress(\Sonata\Component\Customer\AddressInterface $address = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryAddress', array($address));

        return parent::setDeliveryAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryAddress', array());

        return parent::getDeliveryAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethod(\Sonata\Component\Payment\PaymentInterface $method = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethod', array($method));

        return parent::setPaymentMethod($method);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethod', array());

        return parent::getPaymentMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress(\Sonata\Component\Customer\AddressInterface $address = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', array($address));

        return parent::setBillingAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', array());

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function isAddable(\Sonata\Component\Product\ProductInterface $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAddable', array($product));

        return parent::isAddable($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getBasketElements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBasketElements', array());

        return parent::getBasketElements();
    }

    /**
     * {@inheritDoc}
     */
    public function countBasketElements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'countBasketElements', array());

        return parent::countBasketElements();
    }

    /**
     * {@inheritDoc}
     */
    public function hasBasketElements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasBasketElements', array());

        return parent::hasBasketElements();
    }

    /**
     * {@inheritDoc}
     */
    public function getElement(\Sonata\Component\Product\ProductInterface $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElement', array($product));

        return parent::getElement($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getElementByPos($pos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElementByPos', array($pos));

        return parent::getElementByPos($pos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeElements(array $elementsToRemove)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeElements', array($elementsToRemove));

        return parent::removeElements($elementsToRemove);
    }

    /**
     * {@inheritDoc}
     */
    public function removeElement(\Sonata\Component\Basket\BasketElementInterface $element)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeElement', array($element));

        return parent::removeElement($element);
    }

    /**
     * {@inheritDoc}
     */
    public function addBasketElement(\Sonata\Component\Basket\BasketElementInterface $basketElement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBasketElement', array($basketElement));

        return parent::addBasketElement($basketElement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBasketElement(\Sonata\Component\Basket\BasketElementInterface $element)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBasketElement', array($element));

        return parent::removeBasketElement($element);
    }

    /**
     * {@inheritDoc}
     */
    public function hasRecurrentPayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRecurrentPayment', array());

        return parent::hasRecurrentPayment();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal($vat = false, $recurrentOnly = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array($vat, $recurrentOnly));

        return parent::getTotal($vat, $recurrentOnly);
    }

    /**
     * {@inheritDoc}
     */
    public function getVatAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVatAmount', array());

        return parent::getVatAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getVatAmounts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVatAmounts', array());

        return parent::getVatAmounts();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryPrice($vat = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryPrice', array($vat));

        return parent::getDeliveryPrice($vat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryVat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryVat', array());

        return parent::getDeliveryVat();
    }

    /**
     * {@inheritDoc}
     */
    public function hasProduct(\Sonata\Component\Product\ProductInterface $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasProduct', array($product));

        return parent::hasProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function buildPrices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'buildPrices', array());

        return parent::buildPrices();
    }

    /**
     * {@inheritDoc}
     */
    public function clean()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clean', array());

        return parent::clean();
    }

    /**
     * {@inheritDoc}
     */
    public function getSerializationFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerializationFields', array());

        return parent::getSerializationFields();
    }

    /**
     * {@inheritDoc}
     */
    public function getUnserializationFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnserializationFields', array());

        return parent::getUnserializationFields();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($data));

        return parent::unserialize($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryAddressId($deliveryAddressId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryAddressId', array($deliveryAddressId));

        return parent::setDeliveryAddressId($deliveryAddressId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryAddressId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryAddressId', array());

        return parent::getDeliveryAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddressId($billingAddressId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddressId', array($billingAddressId));

        return parent::setBillingAddressId($billingAddressId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddressId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddressId', array());

        return parent::getBillingAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethodCode($paymentMethodCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethodCode', array($paymentMethodCode));

        return parent::setPaymentMethodCode($paymentMethodCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethodCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethodCode', array());

        return parent::getPaymentMethodCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryMethodCode($deliveryMethodCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryMethodCode', array($deliveryMethodCode));

        return parent::setDeliveryMethodCode($deliveryMethodCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryMethodCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryMethodCode', array());

        return parent::getDeliveryMethodCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\Sonata\Component\Customer\CustomerInterface $customer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerId($customerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerId', array($customerId));

        return parent::setCustomerId($customerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', array());

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function getOptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptions', array());

        return parent::getOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptions($options)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptions', array($options));

        return parent::setOptions($options);
    }

    /**
     * {@inheritDoc}
     */
    public function getOption($name, $default = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOption', array($name, $default));

        return parent::getOption($name, $default);
    }

    /**
     * {@inheritDoc}
     */
    public function setOption($name, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOption', array($name, $value));

        return parent::setOption($name, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocale', array($locale));

        return parent::setLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocale', array());

        return parent::getLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency(\Sonata\Component\Currency\CurrencyInterface $currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function getPositions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPositions', array());

        return parent::getPositions();
    }

}
